Added Crash 4, and made everything alphabetical (by name)
dafzor/bnetlauncher pull request #54
Opened 2021-03-27 00:29 UTC by jacobmix

Added Crash Bandicoot 4: It's About Time, and made everything alphabetical by their game name.

2021-03-27 17:40 UTC, dafzor commented
games.ini order was more based of client used. That said, Crash Bandicoot is not included on readme.

2021-03-28 16:32 UTC, jacobmix commented
Mainly just wanted to makes it easier for the community to add games to games.ini themselves.
Easier to sort through it since it's alphabetical. I just added crash since i owned it.
Didn't add Crash 4 to the readme tho as i assume that's just a minimal example. Doesn't include all games or ptr versions.
Don't know if this changes the games.ini.example file tho. But i assume it just copies it over.

2021-03-29 18:46 UTC, dafzor commented
The readme is actually the full "official" supported list of games.

While I've expanded the scope of bnetlauncher with epic client support it hasn't been mentioned beyond advanced configuration with the bundled examples simply being the games I play.

2021-03-31 18:12 UTC, jacobmix commented
Alright. Added Crash Bandicoot 4 to the readme.
May be a good idea to also sort by launcher.
I'll probably edit the gamesdb.ini later tonight or tomorrow for that.

2021-04-02 10:16 UTC, dafzor requested changes

2021-04-02 10:16 UTC, dafzor commented on README.md
> +|wlby           | Crash Bandicoot 4: It's About Time                    |
Should be cb4 not wlby

2021-04-02 14:19 UTC, merged